# Use postgres/example user/password credentials

services:
  db:
    image: postgres:14.5
    container_name: cmd-coleta-clone
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  redis:
    image: redis:latest
    container_name: redis-cmd
    ports:
      - "6380:6379"
    command: redis-server --requirepass "12345678"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
